### ISSUE TITLE
BlazorBook-BlazorMultiHead

### ISSUE THREAD

**Issue by royog** [MarimerLLC/BlazorBook#1]
Hi Rocky.

Only the starting-point project, not the completed project, for the MultiHead chapter is checked in it seems. For example the WASM conditional compilation constant is not present, and the "Startup.cs" file in the .Client project is missing in GitHub.

My initial attempt to build the MultiHead solution following instructions in the book did not go well for me (lot's of compilation errors), so I was hoping to see the completed solution to learn where I might have gone wrong.

Can a completed solution be committed to this repository?

Thanks.

Roy

**Comment by rockfordlhotka** [comment]
@royog - Microsoft has changed the way client-side Blazor works rather a lot since the initial version of the book.

I have an update to the book coming soon that discusses the way Microsoft has ultimately decided Blazor will work, but I don't want to publish it until Blazor WebAssembly is actually released (in about 10 days).

The code in the repo is current - it reflects the current way Blazor functions.

For example, Microsoft got rid of `Startup` for client-side Blazor, and now puts all startup code in `Program.cs`. Various other changes have occurred as well.

You should be able to clone this repo and directly open the multihead solution in the latest VS2019 preview with the latest VS templates installed as described in https://blazor.net.

As I say, the updated instructions for chapter 6 will be available in about 10 days.

**Comment by royog** [comment]
Awesome. That's what I was suspecting.

It's gotta be difficult to keep up a book that describes a fast moving target!

Is there a proper channel to make errata suggestions for your new books?

Roy
Denver, Colorado
________________________________

**Comment by rockfordlhotka** [comment]
This repo is a good channel. Also there's an errata email address listed at in the first section of the book and that works too.

(I emailed you the updated chapter 6, hopefully useful right now, and I'd appreciate any errata you might discover)
